name:                plotly-hs
version:             0.1.0.0
github:              "augustunderground/plotly-hs"
license:             BSD3
author:              "Yannick Uhlmann"
maintainer:          "augustunderground@pm.me"
copyright:           "2023 Yannick Uhlmann"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/augustunderground/plotly-hs#readme>

dependencies:
- base >= 4.7 && < 5
- random
- bytestring
- aeson
- lens

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  plotly-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plotly-hs
    when:
    - condition: false
      other-modules: Paths_plotly-hs

tests:
  plotly-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plotly-hs
