resolver: lts-18.28
compiler: ghc-8.10.7

packages:
- .

ghc-options:
  "$locals": -funfolding-use-threshold=16 -fexcess-precision -optc-O3 -optc-ffast-math -O2 # -v

extra-deps: []

extra-include-dirs: []

extra-lib-dirs: []
